[package]
name = "gotham_pool_test"
version = "0.1.0"
authors = ["Sam Stelfox <sstelfox@bedroomprogrammers.net>"]
edition = "2018"

[dependencies]
gotham = "^0.3"
gotham_derive = "^0.3"
hyper = "^0.12"
mime = "^0.3"

r2d2 = "^0.8"
r2d2_redis = "^0.8"
redis = "^0.9"
